# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = ["github.com/russross/blackfriday"]

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/captcha"

[[constraint]]
  name = "github.com/disintegration/imaging"
  version = "1.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/ego008/youdb"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.1"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/github_flavored_markdown"

[[constraint]]
  branch = "master"
  name = "github.com/russross/blackfriday"

[[constraint]]
  name = "github.com/terminus2049/2049bbs"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/weint/config"

[[constraint]]
  branch = "master"
  name = "github.com/weint/httpclient"

[[constraint]]
  branch = "master"
  name = "github.com/xi2/httpgzip"

[[constraint]]
  name = "github.com/yanyiwu/gojieba"
  version = "1.1.0"

[[constraint]]
  name = "goji.io"
  version = "2.0.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true
